export const REGISTSTORE = 'REGISTSTORE'
export const GETMYSTORE = 'GETMYSTORE'
export const STORELOGIN = 'STORELOGIN'
export const USERLOGIN = 'USERLOGIN'
export const USERREGIST = 'USERREGIST'
export const ADDSHOP = 'ADDSHOP'

export const UPDATASHOPS = 'UPDATASHOPS'

export const LOGOUT = "LOGOUT"

export const DELSHOPS = 'DELSHOPS'

export const GETSTORES = 'GETSTORES'

export const USERCHOOSE = 'USERCHOOSE'

export const UPDATASHOPCAR = 'UPDATASHOPCAR'
export const DELSHOPCAR = 'DELSHOPCAR'

export const APPLY = 'APPLY'
export const CLEARSHOPCAR = 'CLEARSHOPCAR'
export const CREATEORDER = 'CREATEORDER'
export const GETUSERORDERS = 'GETUSERORDERS'
export const GETSTOREORDERS = 'GETSTOREORDERS'
export const CHANGEORDERSTATUS = 'CHANGEORDERSTATUS'